name: Code Review Suggestions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make code suggestions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            // Get the PR diff
            const { data: files } = await github.rest.pulls.listFiles({
              owner,
              repo,
              pull_number,
            });
            
            // Example: Suggest adding console.log statements to functions
            for (const file of files) {
              if (file.filename.endsWith('.tsx')) {
                const { data: content } = await github.rest.repos.getContent({
                  owner,
                  repo,
                  path: file.filename,
                  ref: context.payload.pull_request.head.sha,
                });
                
                const fileContent = Buffer.from(content.content, 'base64').toString();
                const lines = fileContent.split('\n');
                
                // Find function declarations without console.log
                lines.forEach((line, index) => {
                  if (line.includes('function') && !lines[index + 1]?.includes('console.log')) {
                    await github.rest.pulls.createReviewComment({
                      owner,
                      repo,
                      pull_number,
                      commit_id: context.payload.pull_request.head.sha,
                      path: file.filename,
                      line: index + 1,
                      body: '```suggestion\n' + line + '\n  console.log("Function called");\n```\nConsider adding a log statement for debugging purposes.',
                    });
                  }
                });
              }
            }
